### ISSUE TITLE
Custom datasets in another language

### ISSUE THREAD

**Issue by Ajtak** [balcilar/Audio-Captcha-Recognition#3]
Hi, how I create custom matrix file? 
I'm installed matlab, but i dont know steps for build custom datasets. Its possible?

**Comment by balcilar** [comment]
Hello. As you can see our dataset was prepared in Matlab mat format. Because another partner of that project prepared it in Matlab. So in that repository, I just import that training dataset and train the SVM model. In order to some license issues, I am not allowed to share data preparation code publicly. 

On the other hand, it is not a really big deal. If you have enough number of train speech file and you know where the numbers are started and ended, you can modify my python code (especially RastaPLP feature extraction code ) and create your custom train set. However, you need to write your own code.
